function Ik = radar_MI(mu, beta, PR, sigma_RR2, sigma_n2)

    c = sigma_n2 / (beta * PR * sigma_RR2);

    integrand = @(x) ...
        exp(-x.^2) .* ...
        ( mu .* exp(mu.*x.^2 + c) .* expint(mu.*x.^2 + c) ) ...
        .* 2 .* x;    % dt = 2x dx

    Ik = (1/log(2)) * integral(integrand, 0, Inf, ...
         'RelTol',1e-6,'AbsTol',1e-9);
end
